spring:
  h2:
    console:
      path: /h2_console
  datasource: 
    url: jdbc:h2:file:~/h2/testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2: 
      client: 
        registration: 
          azure: 
            client-id: 9b7083d0-1ccf-428f-ae3b-dbde86dc4757
            client-secret: 9KteTr7KWpEpYm2MVjfr1qGjolnahF6kHKy8gLuE+F4=
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid, https://graph.microsoft.com/user.read
            client-name: Azure
            provider: azure            
        provider: 
          azure:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/token
            user-info-uri: https://login.microsoftonline.com/common/openid/userinfo
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys
            user-name-attribute: name

azure:
  activedirectory:
    tenant-id: fa7ae391-d71f-4fb1-bb15-8630a26ae052
    active-directory-groups: Admins, Users

logging:
  level:
    org: 
      springframework.web: INFO
      hibernate: INFO
    com:
      lumi: DEBUG
    user.registry.url: http://localhost:8081/registry/user    

