server: 
  port: 8081
  
spring:
  h2:
    console:
      path: /h2_console
  datasource: 
    url: jdbc:h2:mem:~/h2/regdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    hibernate: 
      ddl-auto: create-drop
      
logging:
  level:
    org: 
      springframework.web: INFO
      hibernate: INFO
    com:
      lumi: DEBUG      